version: '3.9'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    ports:
      - "${DATABASE_DOCKER_PORT}:${DATABASE_PORT}"
    volumes:
      - trick-db:/var/lib/mysql

  web:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
  
volumes:
  trick-db: